apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: varnish
  labels:
    app: varnish
    tier: cache
    k8s/version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: varnish
      tier: cache
      k8s/version: v1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: varnish
        tier: cache
        k8s/version: v1
    spec:
      containers:
      - name: varnish
        image: rochacon/varnish:latest
        livenessProbe:
          initialDelaySeconds: 30
          httpGet:
            path: /
            port: 80
            scheme: HTTP
        ports:
        - containerPort: 80
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /
            port: 80
            scheme: HTTP
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 50m
            memory: 200Mi
        volumeMounts:
        - name: varnish-config
          mountPath: /etc/varnish
      restartPolicy: Always
      volumes:
        - name: varnish-config
          configMap:
            name: varnish-config
