apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
    tier: database
    version: v5.7.14
    k8s/version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
        app: mysql
        tier: database
        version: v5.7.14
        k8s/version: v1
  template:
    metadata:
      labels:
        app: mysql
        tier: database
        version: v5.7.14
        k8s/version: v1
    spec:
      containers:
      - name: mysql
        image: mysql:5.7.14
        env:
        # FIXME user/pass from secret
        - name: MYSQL_ROOT_PASSWORD
          value: root
          # valueFrom:
          #    secretKeyRef:
          #      name: mysql-secrets
          #      key: root-password
        - name: MYSQL_DATABASE
          value: wordpress
        - name: MYSQL_PASSWORD
          value: root
        - name: MYSQL_USER
          value: root
        ports:
        - containerPort: 3306
          protocol: TCP
        livenessProbe:
          initialDelaySeconds: 40
          tcpSocket:
            port: 3306
          timeoutSeconds: 1
        readinessProbe:
          tcpSocket:
            port: 3306
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 1.0
            memory: 2Gi
          requests:
            cpu: 0.1
            memory: 1Gi
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
      volumes:
      - name: data
        emptyDir: {}
