apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
    tier: application
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: wordpress
    tier: application
  type: LoadBalancer
